# Creating simple neural network using python.

In [2]:
#import packages
import numpy as np

In [40]:
#define the sigmoid function
def nonlin(x, deriv=False):
    if (deriv == True):
        return x*(1-x)
    return (1/(1+ np.exp(-x)))

In [41]:
#Input Training Data
X = np.array([
 [0,0,1],
 [0,1,1],
 [0,1,0],
 [1,1,1]
])

In [42]:
#Output Training Data
y = np.array ([[0,0,1,1]]).T
y

array([[0],
       [0],
       [1],
       [1]])

In [43]:
##Inislize the weights randomly (we have three) 
W =  2*np.random.random((3,1))-1
W

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [44]:
#Fix the seed so we will have always the same random values for each run
np.random.seed(1)

In [45]:
##The number of epochs (cycle, iterations) can be changed, here we used 50. 
for iter in range(50):
    z= np.dot(X,W)
    z= nonlin(z)
    error= y-z
    delta_z = error * nonlin(z, True)
    W = W + np.dot(X.T, delta_z)
print("End of Training")
print(" The output is:")
print(z) 

End of Training
 The output is:
[[0.06170633]
 [0.23767843]
 [0.82581122]
 [0.82235165]]
