# Simple Linear Regression lab1

In [1]:
#import pacakges
import numpy as np
from sklearn.linear_model import LinearRegression


In [7]:
# Provide Data
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])
print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [8]:
# Create a model and fit it
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [10]:
#result
score = model.score(x,y)
print(score)

0.715875613747954


In [11]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [12]:
print('slope:', model.coef_)

slope: [0.54]


In [13]:
# Predict 
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
