# Creating simple neural network using python.


In [6]:
#import paskages
import numpy as np


In [7]:
# definition sigmoid
def nonline(x ,deriv=False):
    if (deriv==True):
        return x*(1-x)
    return (1/1+np.exp(-x))

In [9]:
#Input Training Data
X = np.array([
 [0,0,1],
 [0,1,1],
 [0,1,0],
 [1,1,1]])


In [12]:
y = np.array ([[0,0,1,1]]).T
y

array([[0],
       [0],
       [1],
       [1]])

In [13]:
#Inislize the weights randomly (we have three)
W = 2 * np.random.random ((3,1)) -1
W

array([[ 0.5730655 ],
       [ 0.88799304],
       [-0.6395476 ]])

In [14]:
#Fix the seed 
np.random.seed(1)

In [21]:
##
for i in range(50):
    z=np.dot(X,W)
    z=nonline(z)
    error = y-z
    
    delta_z = error * nonline(z,True)
    
    W=W+np.dot(X.T,delta_z)
    print(z)

[[2.89562311]
 [1.78001242]
 [1.41148075]
 [1.43976669]]
[[1.00000002]
 [1.        ]
 [1.020716  ]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02070693]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02069786]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02068882]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02067978]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02067075]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02066174]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02065274]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02064375]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02063477]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02062581]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02061686]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02060791]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02059898]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02059006]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1.02058116]
 [1.        ]]
[[1.00000002]
 [1.        ]
 [1