# Lab activity MLP

In [4]:
#import paskages
import numpy as np

In [14]:
#weights
w=np.array([[0.11 , 0.12  ],[0.21, 0.08]])

In [15]:
#inputs data 
X=np.array([[2],[3]])
X

array([[2],
       [3]])

In [16]:
#Y
y=1 

In [17]:
#alpha =a 
a= 0.05

In [18]:
X.shape

(2, 1)

In [47]:
b=round(0.05*(-0.809),3)
b

-0.04

In [48]:
V=np.array([0.14,0.15])

In [49]:
wn=np.round(b*(X*V),3)

In [50]:
wn

array([[-0.011, -0.012],
       [-0.017, -0.018]])

In [53]:
np.round(w- wn,2)

array([[0.12, 0.13],
       [0.23, 0.1 ]])