# Quadratic Feature Map


In [2]:
#import packages
import numpy as np

In [10]:

def quadratic_feature_map(x):
    n = x.shape[0]
    quadratic_features = []
    for i in range(n):
        quadratic_features.append(x[i]**2)
        for j in range(i+1, n):
            quadratic_features.append(x[i]*x[j])
    return np.array(quadratic_features)

# Example usage
x = np.array([5,10])
quadratic_x = quadratic_feature_map(x)
print(quadratic_x) 

[ 25  50 100]


In [11]:
# Example usage
x = np.array([3,5])
quadratic_x = quadratic_feature_map(x)
print(quadratic_x) 

[ 9 15 25]


In [12]:
# Example usage
x = np.array([3,5,10])
quadratic_x = quadratic_feature_map(x)
print(quadratic_x) 

[  9  15  30  25  50 100]
